export const namespaced = true;

export const state = {
  schools: [
    "Ecumenical",
    "Spiritism",
  ],
  spells: [
    {
      spell: "Spurt",
      school: "Ecumenical",
      min: 0,
      max: 15,
      chance: 0,
      price: 10,
      location: "Magic Vendor",
    }, {
      spell: "Transcendental Seance",
      school: "Spiritism",
      min: 0,
      max: 15,
      chance: 0,
      price: 100,
      location: "Magic Vendor",
    }, {
      spell: "Lesser Heal",
      school: "Ecumenical",
      min: 0,
      max: 25,
      chance: 0,
      price: 25,
      location: "Magic Vendor",
    }, {
      spell: "Expel Spirit",
      school: "Spiritism",
      min: 0,
      max: 25,
      chance: 0,
      price: 100,
      location: "Magic Vendor",
    }, {
      spell: "Corruption",
      school: "Ecumenical",
      min: 5,
      max: 30,
      chance: 0,
      price: 40,
      location: "",
    }, {
      spell: "Kau Regeneration",
      school: "Spiritism",
      min: 10,
      max: 35,
      chance: 0,
      price: 50,
      location: "",
    }, {
      spell: "Purify",
      school: "Ecumenical",
      min: 15,
      max: 35,
      chance: 0,
      price: 50,
      location: "",
    }, {
      spell: "Lightning",
      school: "Ecumenical",
      min: 15,
      max: 40,
      chance: 0,
      price: 50,
      location: "",
    }, {
      spell: "Ether Momentum",
      school: "Spiritism",
      min: 20,
      max: 45,
      chance: 0,
      price: 100,
      location: "Minotaur Dungeon",
    }, {
      spell: "Outburst",
      school: "Ecumenical",
      min: 20,
      max: 45,
      chance: 0,
      price: 100,
      location: "",
    }, {
      spell: "Ether Barrier",
      school: "Spiritism",
      min: 30,
      max: 55,
      chance: 0,
      price: 500,
      location: "Risar Dungeon",
    }, {
      spell: "Mind Blast",
      school: "Ecumenical",
      min: 30,
      max: 55,
      chance: 0,
      price: 70,
      location: "Bandit Caster",
    }, {
      spell: "Magic Reflection",
      school: "Ecumenical",
      min: 35,
      max: 60,
      chance: 0,
      price: 70,
      location: "",
    }, {
      spell: "Thunderlash",
      school: "Ecumenical",
      min: 40,
      max: 65,
      chance: 0,
      price: 70,
      location: "Bandit Caster",
    }, {
      spell: "Transcendental Awareness",
      school: "Spiritism",
      min: 40,
      max: 65,
      chance: 0,
      price: 500,
      location: "Magic Vendor",
    }, {
      spell: "Mental Healing",
      school: "Spiritism",
      min: 50,
      max: 75,
      chance: 0,
      price: 400,
      location: "Bandit Healer",
    }, {
      spell: "Greater Heal",
      school: "Ecumenical",
      min: 50,
      max: 75,
      chance: 0,
      price: 800,
      location: "Bandit Healer",
    }, {
      spell: "Fulmination",
      school: "Ecumenical",
      min: 60,
      max: 85,
      chance: 0,
      price: 1200,
      location: "Bandit Caster",
    }, {
      spell: "Mental Projectile",
      school: "Spiritism",
      min: 60,
      max: 85,
      chance: 0,
      price: 20000,
      location: "Sator Dungeon",
    }, {
      spell: "Flame Strike",
      school: "Ecumenical",
      min: 70,
      max: 95,
      chance: 0,
      price: 1000,
      location: "Bandit Caster",
    }, {
      spell: "Dispel Portal",
      school: "Spiritism",
      min: 70,
      max: 100,
      chance: 0,
      price: 700,
      location: "Bandit Caster",
    }, {
      spell: "Earthquake",
      school: "Ecumenical",
      min: 75,
      max: 100,
      chance: 0,
      price: 8500,
      location: "Veteran Bandit Caster, Alchemist Bowman, Illusionist",
    }, {
      spell: "Resurrect",
      school: "Spiritism",
      min: 75,
      max: 100,
      chance: 0,
      price: 1000,
      location: "Magic Vendor",
    }, {
      spell: "Etherworld Portal",
      school: "Spiritism",
      min: 80,
      max: 100,
      chance: 0,
      price: 0,
      location: "Spiritism Trader (Forest Troll Head)",
    }
  ]
};

export const getters = {
  getSchools: (state) => state.schools,
  getSpells: (state) => state.spells,
  getSpellsBySchools: (state) => (schools) => state.spells.filter((spell) => schools.includes(spell.school)),
};
